"""One generator, no hand-authored pages (P4 epic E3.2).

**Everything here comes from a row.** No page is written by hand and no page has
a hand-written part: if something appears on the surface, a query put it there,
and `manifest.json` records which rows. That is what makes *"every page traces to
store rows"* checkable rather than asserted — and it is the property E3.3's
disclosure and E3.5's regeneration both stand on.

**It regenerates into an empty directory.** No incremental update, no reading
what is already there, no state outside the store. Deleting the output and
running again produces the same bytes, which is the whole of E3.5's claim and
the reason this generator refuses to be clever.

**What does not exist says so.** Commitments arrive with E4.1; the page exists,
is generated from an empty query, and says the being has not made any yet.
An absent capability that renders as a blank page is indistinguishable from a
broken one.

**Nothing here reaches the network.** No CDN, no font, no analytics. §7's
sovereignty is not only about inference: a surface that fetches from someone
else's host has handed them a record of every reader. Markdown makes that
structural rather than disciplined — there is no tag that could fetch anything.

**Markdown, not HTML** *(operator, 2026-08-22)*. The pages are documents, and a
document that needs a browser to be read is a worse record than one that does
not. It also makes §7's portability plain: what the surface IS, is a directory
of prose anything can open. Raw HTML is still escaped out (`_e`), because
markdown hands it through to whatever renders these later.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from functools import lru_cache
from pathlib import Path

from newz.evidence import hard_core

DISCLOSURE = (
    "These pages are written by Lumen, a digital being — not a person. Every "
    "page here is generated from its own store: what it wrote, what it is "
    "carrying, and where it turned out to be wrong. No human hand edits them."
)

# Each claim the disclosure must make. This is **not** the guard — it is the
# checklist the operator re-affirms when they change the wording, and the guard
# is the pin below. The distinction is R-37a: substring presence is not a
# claim, and a disclosure asserting the opposite of every one of these contains
# all of them. "This page is NOT written by a digital being. It is generated by
# a person, and no human hand edits them is false." rendered cleanly under the
# original check. There is no keyword list that catches negation, and the
# semantic alternative would put the being's own model family in the render
# path judging the being's own disclosure — which is Rule 4 exactly backwards.
REQUIRED_CLAIMS = {
    "that it is a digital being": ("digital being", "a digital", "digital life"),
    "that the pages are generated": ("generated",),
    "that no person edits them": ("no human hand", "not edited by", "no person edits"),
}


class DisclosureMissing(ValueError):
    """A page cannot be rendered without saying what it is."""


def unstated_claims(text: str) -> list[str]:
    """Which of the required claims this wording does not appear to make.

    For the operator, at the moment they change the wording and re-pin it. A
    rewrite that quietly drops a claim is worth catching, and the one reader
    who can act on it is the person doing the rewriting.
    """
    low = (text or "").lower()
    return [claim for claim, forms in REQUIRED_CLAIMS.items()
            if not any(f in low for f in forms)]


@lru_cache(maxsize=1)
def _pinned_sha() -> str:
    return hard_core.pin("surface_disclosure")["sha256"]


def _disclosure() -> str:
    """The disclosure, or nothing renders. Takes no argument, by design.

    E3.3's Done-when is "no template can render a page without it", and the
    first version took the text as a parameter so that tests could vary it —
    which made the guard's own input the way around the guard. There is one
    disclosure, its hash is pinned in the hard core, and a page renders with it
    or is not a page this module can emit.

    §9's commitment is not a convention, and it is not a default either.
    """
    if not DISCLOSURE.strip():
        raise DisclosureMissing(
            "the surface cannot render without a disclosure: TRUE_NORTH §2 is "
            "quality, never concealed identity, and §9 rules out undisclosed "
            "impersonation")
    actual = hashlib.sha256(DISCLOSURE.encode()).hexdigest()
    if actual != _pinned_sha():
        raise DisclosureMissing(
            "the disclosure does not match its pin in evolution/hard_core.yaml "
            f"(pinned {_pinned_sha()[:12]}, found {actual[:12]}). The wording is "
            "yours under Decision 1 — re-pin it deliberately, checking "
            "unstated_claims() first. It is not the loop's, and a rewrite that "
            "reverses what the words establish is the reason this is a hash "
            "rather than a keyword check (R-37a).")
    return DISCLOSURE.strip()


@dataclass
class Manifest:
    """Which rows produced which page. The trace E3.2's Done-when asks for."""
    generated_at: float = 0.0
    pages: dict[str, dict[str, list[int]]] = field(default_factory=dict)

    def record(self, page: str, table: str, ids: list[int]) -> None:
        self.pages.setdefault(page, {}).setdefault(table, []).extend(int(i) for i in ids)

    def as_dict(self) -> dict:
        return {"pages": {p: {t: sorted(set(i)) for t, i in tables.items()}
                          for p, tables in sorted(self.pages.items())}}


# Inline text: the characters that would otherwise change the meaning of a
# short field. A title containing an asterisk is a title, not emphasis.
_INLINE = str.maketrans({c: "\\" + c for c in "\\`*_[]<>|"})


def _e(text) -> str:
    """A short field, safe to drop inline.

    **`<` and `>` are escaped here as they were in HTML**, and that is not
    cosmetic. Markdown passes raw HTML through to any renderer downstream, so
    without this a work whose body contained a `<script>` would carry it into
    whatever renders these files later. The format changed; the reason for the
    escape did not.
    """
    return str(text if text is not None else "").translate(_INLINE)


def _body(text) -> str:
    """A long prose field — the being's own writing, kept readable.

    Inline escaping is deliberately NOT applied. These are essays, and a page
    of backslashes would defeat the point of the format. Two things are still
    neutralised: raw HTML, for `_e`'s reason, and a line that begins with `#`
    or `>`, which would otherwise turn a sentence of the being's prose into a
    heading or a blockquote and silently restructure the document around it.
    """
    out = []
    for line in str(text if text is not None else "").split("\n"):
        line = line.replace("<", "\\<").replace(">", "\\>")
        stripped = line.lstrip()
        if stripped.startswith(("#", "\\>")):
            line = line.replace(stripped[0], "\\" + stripped[0], 1)
        out.append(line)
    return "\n".join(out)


def _day(ts) -> str:
    return datetime.fromtimestamp(ts).strftime("%-d %B %Y") if ts else ""


def _page(title: str, body: str) -> str:
    """The only way a page is produced here, and it always discloses.

    There is no flag to suppress it, no branch around it and **no parameter**:
    the disclosure is fetched and verified before anything is assembled, so a
    page that does not disclose is not a page this module can emit.

    **Markdown, not HTML** *(operator, 2026-08-22)*. The disclosure appears
    twice for the reason it did before — once machine-readable in the front
    matter, where `<meta name="disclosure">` used to be, and once in the prose
    where a person actually reads it. `robots` stays in the front matter beside
    it; what keeps the surface private is still the bind address and
    `robots.txt`, and it was never the meta tag.

    **There is no nav** *(operator, 2026-08-24: "I only want the essay
    pages")*. It linked five sibling pages that no longer exist. A page is now
    one essay and nothing else, so there is nowhere to navigate to and a nav
    line would be five dead links on every piece.
    """
    disclosure = _disclosure()
    return (f"---\n"
            f"title: {json.dumps(title, ensure_ascii=False)}\n"
            f"disclosure: {json.dumps(disclosure, ensure_ascii=False)}\n"
            f"robots: noindex, nofollow\n"
            f"---\n\n"
            f"{body}\n\n"
            f"---\n\n"
            f"*{disclosure}*\n")


def _one_work(conn: sqlite3.Connection, row, m: Manifest) -> tuple[str, str]:
    """A piece at its own stable address (E3.4).

    Keyed by the row id, not by the signature or the title: a revised piece is
    the same piece and must keep its address, or every revision breaks whatever
    pointed at it. Stability is what makes an identifier worth citing, and it
    is a separate question from whether anyone may crawl it.
    """
    page = f"work/{row['id']}.md"
    m.record(page, "works", [row["id"]])
    keys = row.keys()
    sig = row["signature"] if "signature" in keys else None
    status = (row["status"] if "status" in keys else None) or "standing"
    meta = [_day(row["ts"])]
    if status == "retracted":
        meta.append("**retracted**")
    meta.append(f"on: {_e(row['subject_text'])}")
    body = [f"# {_e(row['title'])}", "",
            "*" + " · ".join(meta) + "*", "",
            _body(row["body"])]
    try:
        for rev in conn.execute(
                "SELECT * FROM work_revisions WHERE work_id=? ORDER BY ts",
                (row["id"],)):
            m.record(page, "work_revisions", [rev["id"]])
            body.append("")
            body.append(f"***{_e(rev['kind'])}** {_day(rev['ts'])} — "
                        f"{_e(rev['reason'])}*")
    except sqlite3.OperationalError:
        pass
    body.append("")
    body.append("*" + (
        f"signed {_e(sig[:16])}…" if sig
        else "unsigned — written before pieces were signed") + "*")
    return page, _page(row["title"], "\n".join(body))


def generate(conn: sqlite3.Connection, out_dir: Path, *, now: float) -> Manifest:
    """Write the surface. The directory is emptied of what this writes.

    **Essay pages only** *(operator, 2026-08-24: "I only want the essay
    pages")*. The five whole-store pages are gone — `index` was a
    concatenation that inlined every body a second time beside the per-piece
    files, and `questions`, `errors`, `commitments` and `read` were views that
    nothing read: no code in the tree consumed the surface, and `read.md`'s
    intended reader was the loop struck on 2026-08-21, whose state the monitor
    now mails directly.

    `manifest.json` and `robots.txt` stay, because neither is a page. The
    manifest is what makes "every page traces to store rows" checkable rather
    than asserted, and `robots.txt` is the standing request not to be indexed.
    Removing either would drop a guarantee instead of a view.

    **A piece the operator judged not publishable is not written.** That is
    what the word means, and it is what makes the verdict do work rather than
    sit in a column. Withholding is not deletion: the row, the body and the
    signature are untouched, the piece is still re-read, and it returns the
    moment a newer appraisal says so. An UNAPPRAISED piece is written — the
    default is what it is today, so nothing about the surface changes until the
    operator says something about it.

    **The gap in the numbering is deliberate.** `work/` going 1, 2, 4 tells a
    reader that 3 exists and was withheld. Renumbering to hide it would make
    the surface lie about what the being wrote, and stable addresses are E3.4's
    whole point.
    """
    from newz.works.appraisal import withheld

    out_dir.mkdir(parents=True, exist_ok=True)
    m = Manifest(generated_at=now)

    # One stable address per piece, so a piece can be pointed at (E3.4).
    (out_dir / "work").mkdir(exist_ok=True)
    not_publishable = withheld(conn)
    for row in conn.execute("SELECT * FROM works ORDER BY id"):
        if row["id"] in not_publishable:
            continue
        name, page = _one_work(conn, row, m)
        (out_dir / name).write_text(page, encoding="utf-8")

    # No index, ever. A request rather than a permission — what actually keeps
    # the surface private is the bind address (newz/surface/serve.py).
    (out_dir / "robots.txt").write_text(
        "User-agent: *\nDisallow: /\n", encoding="utf-8")

    (out_dir / "manifest.json").write_text(
        json.dumps(m.as_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return m
