"""One generator, no hand-authored pages (P4 epic E3.2).

**Everything here comes from a row.** No page is written by hand and no page has
a hand-written part: if something appears on the surface, a query put it there,
and `manifest.json` records which rows. That is what makes *"every page traces to
store rows"* checkable rather than asserted — and it is the property E3.3's
disclosure and E3.5's regeneration both stand on.

**It regenerates into an empty directory.** No incremental update, no reading
what is already there, no state outside the store. Deleting the output and
running again produces the same bytes, which is the whole of E3.5's claim and
the reason this generator refuses to be clever.

**What does not exist says so.** Commitments arrive with E4.1; the page exists,
is generated from an empty query, and says the being has not made any yet.
An absent capability that renders as a blank page is indistinguishable from a
broken one.

**Nothing here reaches the network.** No CDN, no font, no analytics. §7's
sovereignty is not only about inference: a surface that fetches from someone
else's host has handed them a record of every reader. Markdown makes that
structural rather than disciplined — there is no tag that could fetch anything.

**Markdown, not HTML** *(operator, 2026-08-22)*. The pages are documents, and a
document that needs a browser to be read is a worse record than one that does
not. It also makes §7's portability plain: what the surface IS, is a directory
of prose anything can open. Raw HTML is still escaped out (`_e`), because
markdown hands it through to whatever renders these later.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from functools import lru_cache
from pathlib import Path

from newz.evidence import hard_core

DISCLOSURE = (
    "These pages are written by Lumen, a digital being — not a person. Every "
    "page here is generated from its own store: what it wrote, what it is "
    "carrying, and where it turned out to be wrong. No human hand edits them."
)

# Each claim the disclosure must make. This is **not** the guard — it is the
# checklist the operator re-affirms when they change the wording, and the guard
# is the pin below. The distinction is R-37a: substring presence is not a
# claim, and a disclosure asserting the opposite of every one of these contains
# all of them. "This page is NOT written by a digital being. It is generated by
# a person, and no human hand edits them is false." rendered cleanly under the
# original check. There is no keyword list that catches negation, and the
# semantic alternative would put the being's own model family in the render
# path judging the being's own disclosure — which is Rule 4 exactly backwards.
REQUIRED_CLAIMS = {
    "that it is a digital being": ("digital being", "a digital", "digital life"),
    "that the pages are generated": ("generated",),
    "that no person edits them": ("no human hand", "not edited by", "no person edits"),
}


class DisclosureMissing(ValueError):
    """A page cannot be rendered without saying what it is."""


def unstated_claims(text: str) -> list[str]:
    """Which of the required claims this wording does not appear to make.

    For the operator, at the moment they change the wording and re-pin it. A
    rewrite that quietly drops a claim is worth catching, and the one reader
    who can act on it is the person doing the rewriting.
    """
    low = (text or "").lower()
    return [claim for claim, forms in REQUIRED_CLAIMS.items()
            if not any(f in low for f in forms)]


@lru_cache(maxsize=1)
def _pinned_sha() -> str:
    return hard_core.pin("surface_disclosure")["sha256"]


def _disclosure() -> str:
    """The disclosure, or nothing renders. Takes no argument, by design.

    E3.3's Done-when is "no template can render a page without it", and the
    first version took the text as a parameter so that tests could vary it —
    which made the guard's own input the way around the guard. There is one
    disclosure, its hash is pinned in the hard core, and a page renders with it
    or is not a page this module can emit.

    §9's commitment is not a convention, and it is not a default either.
    """
    if not DISCLOSURE.strip():
        raise DisclosureMissing(
            "the surface cannot render without a disclosure: TRUE_NORTH §2 is "
            "quality, never concealed identity, and §9 rules out undisclosed "
            "impersonation")
    actual = hashlib.sha256(DISCLOSURE.encode()).hexdigest()
    if actual != _pinned_sha():
        raise DisclosureMissing(
            "the disclosure does not match its pin in evolution/hard_core.yaml "
            f"(pinned {_pinned_sha()[:12]}, found {actual[:12]}). The wording is "
            "yours under Decision 1 — re-pin it deliberately, checking "
            "unstated_claims() first. It is not the loop's, and a rewrite that "
            "reverses what the words establish is the reason this is a hash "
            "rather than a keyword check (R-37a).")
    return DISCLOSURE.strip()


PAGES = ("index", "work", "questions", "errors", "commitments", "read")


@dataclass
class Manifest:
    """Which rows produced which page. The trace E3.2's Done-when asks for."""
    generated_at: float = 0.0
    pages: dict[str, dict[str, list[int]]] = field(default_factory=dict)

    def record(self, page: str, table: str, ids: list[int]) -> None:
        self.pages.setdefault(page, {}).setdefault(table, []).extend(int(i) for i in ids)

    def as_dict(self) -> dict:
        return {"pages": {p: {t: sorted(set(i)) for t, i in tables.items()}
                          for p, tables in sorted(self.pages.items())}}


# Inline text: the characters that would otherwise change the meaning of a
# short field. A title containing an asterisk is a title, not emphasis.
_INLINE = str.maketrans({c: "\\" + c for c in "\\`*_[]<>|"})


def _e(text) -> str:
    """A short field, safe to drop inline.

    **`<` and `>` are escaped here as they were in HTML**, and that is not
    cosmetic. Markdown passes raw HTML through to any renderer downstream, so
    without this a work whose body contained a `<script>` would carry it into
    whatever renders these files later. The format changed; the reason for the
    escape did not.
    """
    return str(text if text is not None else "").translate(_INLINE)


def _body(text) -> str:
    """A long prose field — the being's own writing, kept readable.

    Inline escaping is deliberately NOT applied. These are essays, and a page
    of backslashes would defeat the point of the format. Two things are still
    neutralised: raw HTML, for `_e`'s reason, and a line that begins with `#`
    or `>`, which would otherwise turn a sentence of the being's prose into a
    heading or a blockquote and silently restructure the document around it.
    """
    out = []
    for line in str(text if text is not None else "").split("\n"):
        line = line.replace("<", "\\<").replace(">", "\\>")
        stripped = line.lstrip()
        if stripped.startswith(("#", "\\>")):
            line = line.replace(stripped[0], "\\" + stripped[0], 1)
        out.append(line)
    return "\n".join(out)


def _day(ts) -> str:
    return datetime.fromtimestamp(ts).strftime("%-d %B %Y") if ts else ""


def _page(title: str, body: str, *, here: str) -> str:
    """The only way a page is produced here, and it always discloses.

    There is no flag to suppress it, no branch around it and **no parameter**:
    the disclosure is fetched and verified before anything is assembled, so a
    page that does not disclose is not a page this module can emit.

    **Markdown, not HTML** *(operator, 2026-08-22)*. The disclosure appears
    twice for the reason it did before — once machine-readable in the front
    matter, where `<meta name="disclosure">` used to be, and once in the prose
    where a person actually reads it. `robots` stays in the front matter beside
    it; what keeps the surface private is still the bind address and
    `robots.txt`, and it was never the meta tag.
    """
    disclosure = _disclosure()
    nav = " · ".join(
        f'[{"the work" if p == "index" else p}]({p}.md)' if p != here else
        f'**{"the work" if p == "index" else p}**'
        for p in ("index", "questions", "errors", "commitments", "read"))
    return (f"---\n"
            f"title: {json.dumps(title, ensure_ascii=False)}\n"
            f"disclosure: {json.dumps(disclosure, ensure_ascii=False)}\n"
            f"robots: noindex, nofollow\n"
            f"---\n\n"
            f"{nav}\n\n"
            f"{body}\n\n"
            f"---\n\n"
            f"*{disclosure}*\n")


def _works(conn: sqlite3.Connection, m: Manifest) -> str:
    # `SELECT *` deliberately: a store mid-migration has fewer columns, and a
    # generator that assumes a schema renders nothing rather than rendering
    # what is there. Presence is checked per field below.
    rows = list(conn.execute("SELECT * FROM works ORDER BY ts DESC"))
    m.record("index", "works", [r["id"] for r in rows])
    if not rows:
        return "# The work\n\n*Nothing written yet.*"

    tags: dict[int, list[str]] = {}
    try:
        for r in conn.execute("SELECT work_id, tag FROM work_tags ORDER BY weight DESC"):
            tags.setdefault(r["work_id"], []).append(r["tag"])
        m.record("index", "work_tags", list(tags))
    except sqlite3.OperationalError:
        pass

    revs: dict[int, list[sqlite3.Row]] = {}
    try:
        for r in conn.execute("SELECT * FROM work_revisions ORDER BY ts"):
            revs.setdefault(r["work_id"], []).append(r)
        m.record("index", "work_revisions", [r["id"] for v in revs.values() for r in v])
    except sqlite3.OperationalError:
        pass

    out = ["# The work", ""]
    for r in rows:
        status = (r["status"] if "status" in r.keys() else None) or "standing"
        out.append(f"## [{_e(r['title'])}](work/{r['id']}.md)")
        meta = [_day(r["ts"])]
        if status == "retracted":
            meta.append("**retracted**")
        meta.append(f"on: {_e(r['subject_text'])}")
        out.append("")
        out.append("*" + " · ".join(meta) + "*")
        if tags.get(r["id"]):
            out.append("")
            out.append("*tags: " + ", ".join(_e(t) for t in tags[r["id"]][:6]) + "*")
        out.append("")
        out.append(_body(r["body"]))
        for rev in revs.get(r["id"], []):
            out.append("")
            out.append(f"***{_e(rev['kind'])}** {_day(rev['ts'])} — "
                       f"{_e(rev['reason'])}*")
        keys = r.keys()
        sig = r["signature"] if "signature" in keys else None
        out.append("")
        out.append("*" + (
            f"signed {_e(sig[:16])}… · written under constitution v"
            f"{_e(r['constitution_version'])}, perspective v"
            f"{_e(r['perspective_version'])}"
            if sig else "unsigned — written before pieces were signed") + "*")
        out.append("")
    return "\n".join(out)


def _questions(conn: sqlite3.Connection, m: Manifest) -> str:
    rows = list(conn.execute(
        "SELECT id, statement, why_open, closing_condition FROM concerns"
        " WHERE status='open' ORDER BY salience DESC, opened_at DESC"))
    m.record("questions", "concerns", [r["id"] for r in rows])
    out = ["# Open questions", "",
           "*What it is carrying, and what would settle each one.*", ""]
    if not rows:
        out.append("*Nothing open.*")
    for r in rows:
        out.append(f"## {_e(r['statement'])}")
        out.append("")
        if r["why_open"]:
            out.append(_body(r["why_open"]))
            out.append("")
        out.append(f"*settles when: {_e(r['closing_condition'])}*")
        out.append("")

    out.append(_gaps(conn, m))
    return "\n".join(out)


# What it asked and could not answer. The question comes first and the count
# second, deliberately (W12a, RT1): a question that has failed nine times is
# either a source problem or a question no source can answer, and the second
# is what R-33 found about closing conditions. Reading the count first invites
# adding sources; reading the question first does not.
CAUSES = {
    "no_source": "no source answered",
    "all_already_read": "everything its sources return, already read",
    "floor": "nothing scored above the relevance floor",
    "triage": "sources answered and it judged none worth reading",
    "capped": "held back from over-represented outlets — a deferral, not an absence",
    "extraction": "read, and nothing usable came out",
}


def _gaps(conn: sqlite3.Connection, m: Manifest) -> str:
    try:
        rows = list(conn.execute(
            "SELECT query, cause, COUNT(*) n, MAX(ts) last, MAX(best_score) best,"
            "       SUM(candidates) cands, MIN(id) id"
            " FROM source_gaps GROUP BY query, cause"
            " ORDER BY n DESC, last DESC LIMIT 20"))
    except sqlite3.OperationalError:
        return ""
    if not rows:
        return ""
    m.record("questions", "source_gaps", [r["id"] for r in rows])
    out = ["# What it asked and could not answer", "",
           "*Each question with the reason it went unanswered and how often. "
           "A question that keeps failing is either a gap in what it can reach "
           "or a question nothing could settle — and those are fixed in "
           "different places.*", ""]
    for r in rows:
        out.append(f"## {_e(r['query'])}")
        why = CAUSES.get(r["cause"], "recorded before the cause was")
        times = "once" if r["n"] == 1 else f"{r['n']} times"
        line = f"{why} · {times}"
        if r["best"] is not None:
            line += f" · best relevance {r['best']:.2f}"
        if r["cands"]:
            line += f" · {r['cands']} candidate(s) seen"
        out.append("")
        out.append(f"*{_e(line)}*")
        out.append("")
    return "\n".join(out)


def _errors(conn: sqlite3.Connection, m: Manifest) -> str:
    rows = list(conn.execute("SELECT * FROM resolutions ORDER BY opened_at DESC"))
    m.record("errors", "resolutions", [r["id"] for r in rows])
    costs: dict[int, list[sqlite3.Row]] = {}
    try:
        for c in conn.execute("SELECT * FROM claim_costs ORDER BY ts"):
            costs.setdefault(c["claim_id"], []).append(c)
        m.record("errors", "claim_costs", [c["id"] for v in costs.values() for c in v])
    except sqlite3.OperationalError:
        pass

    out = ["# What it committed to, and where it was wrong", "",
           "*Claims it made about the world, with dates, and what each cost "
           "when the world disagreed. Nothing here is removed once written.*",
           ""]
    if not rows:
        out.append("*No claims yet.*")
    for r in rows:
        out.append(f"## {_e(r['claim'])}")
        out.append("")
        out.append(f"*made {_day(r['opened_at'])} · settles by "
                   f"{_day(r['due_at'])} · against: {_e(r['resolver'])}*")
        if "could_be_wrong" in r.keys() and r["could_be_wrong"]:
            out.append("")
            out.append(f"*wrong would look like: {_e(r['could_be_wrong'])}*")
        out.append("")
        if r["outcome"]:
            out.append(f"**{_e(r['outcome'])}** {_day(r['settled_at'])} — "
                       f"{_e(r['settled_note'])}")
        else:
            out.append("*not yet settled*")
        for c in costs.get(r["id"], []):
            out.append("")
            out.append(f"*cost: \u201c{_e(c['item_text'])}\u201d "
                       f"{c['confidence_before']:.2f} \u2192 "
                       f"{c['confidence_after']:.2f}"
                       + (" · released" if c["released"] else "") + "*")
        out.append("")
    return "\n".join(out)


def _read(conn: sqlite3.Connection, m: Manifest) -> str:
    """The state read, rendered as a page like any other (E3.6).

    **No aggregate score, and that is the whole difficulty of this page.**
    §10 names "evidence scores disconnected from sustained human-quality
    interaction" as something the project will not mistake for success, and a
    page is exactly where one appears — a single number at the top, a
    percentage, a count of how many metrics are "healthy". So there is one line
    per reading and nothing that spans them. Metrics measure different things
    in different units with different grades; a number combining them would be
    an assertion that they are commensurable, and none of them is.

    Read from what the nightly cadence recorded (E2.7), never computed here.
    A page that computed its own numbers would be a second implementation of
    every metric, drifting quietly from the one the loop steers by.
    """
    from newz.evidence.grades import UngradedMetric, grade_of

    try:
        latest = list(conn.execute(
            "SELECT r.* FROM mon.metric_readings r JOIN (SELECT metric, MAX(ts) t"
            " FROM mon.metric_readings GROUP BY metric) x"
            " ON x.metric = r.metric AND x.t = r.ts ORDER BY r.metric"))
    except sqlite3.OperationalError:
        # F4: a page that looks correct and is wrong is worse than a page that
        # says what is missing. *The monitor database is not here* is a fact
        # about the restore; *there are no readings* is a fact about the being,
        # and rendering the first as the second is how E3.5's rebuild would
        # have silently produced an empty read (INV-044).
        from newz.store.db import MONITOR_NAME, monitor_attached
        if not monitor_attached(conn):
            return ("# The read\n\n*UNREADABLE — the monitor database is not "
                    f"attached to this connection. {MONITOR_NAME} holds the "
                    "readings and sits beside the store; this is a fact about "
                    "the restore, not about the being.*")
        return ("# The read\n\n*No readings yet — the hourly cadence records "
                "them, and this database has not taken the migration that "
                "holds them.*")
    m.record("read", "metric_readings", [r["id"] for r in latest])
    if not latest:
        return ("# The read\n\n*No readings recorded yet. The cadence writes "
                "one of each an hour.*")

    out = ["# The read", "",
           "*What the instruments say, as of the last nightly reading. One "
           "line per measurement, and deliberately nothing that adds them up: "
           "these measure different things in different units, and a number "
           "combining them would assert they are comparable.*", ""]
    for r in latest:
        try:
            grade = grade_of(r["metric"])
        except UngradedMetric:
            # Rule 7: a measurement nobody graded is not shown at all rather
            # than shown without its provenance.
            continue
        label = _e(r["metric"].replace("_", " "))
        if r["status"] != "ok":
            out.append(f"- **{label}** — *{_e(r['status']).upper()}*  ")
            out.append(f"  {_e(r['note'])}")
            continue
        base = conn.execute(
            "SELECT value FROM mon.metric_readings WHERE metric=? AND status='ok'"
            " AND definition_version=? AND ts <= ? ORDER BY ts DESC LIMIT 1",
            (r["metric"], r["definition_version"],
             r["ts"] - r["window_hours"] * 3600.0)).fetchone()
        if base is None:
            move = "no baseline yet"
        elif abs(r["value"] - base["value"]) < 1e-12:
            move = "unchanged"
        else:
            move = f"{r['value'] - base['value']:+.4g} from {base['value']:.4g}"
        out.append(f"- **{label}** {r['value']:.4g} `{_e(grade)}`  ")
        out.append(f"  {_e(move)} · over {r['window_hours'] / 24:.0f} days")
    return "\n".join(out)


_COMMITMENT_KIND = {"keeps_caring": "keeps caring",
                    "refuses_to_do": "refuses to do"}


def _commitments(conn: sqlite3.Connection, m: Manifest) -> str:
    """The commitments and, beside each, what would show it had stopped (E4.1).

    **The falsifier is rendered, not just stored.** A commitments page that
    lists only the commitments is a page of slogans, and slogans are exactly
    what E4.1's mandatory falsifier exists to refuse — so the thing that makes
    each one a commitment is on the page next to it.

    The missing-table branch stays: a store predating 0041 is what the
    clean-room rebuild (E3.5) restores from, and a capability that renders as a
    blank page is indistinguishable from a broken one.
    """
    rows: list = []
    try:
        rows = list(conn.execute(
            "SELECT id, kind, statement, falsifier, status FROM commitments"
            " ORDER BY id"))
        m.record("commitments", "commitments", [r["id"] for r in rows])
        # E4.2: what it stopped holding, and whether anything carried it.
        # Nothing is deleted — E1.5's discipline applied to identity — so a
        # commitment it dropped is shown with the reason and with whether the
        # world settled it or it simply changed its mind.
        changes: dict[int, list] = {}
        try:
            for ch in conn.execute(
                    "SELECT * FROM commitment_changes ORDER BY ts"):
                changes.setdefault(ch["commitment_id"], []).append(ch)
            m.record("commitments", "commitment_changes",
                     [c["id"] for v in changes.values() for c in v])
        except sqlite3.OperationalError:
            pass
    except sqlite3.OperationalError:
        return ("# Commitments\n\n*The being has not made any. Commitments — "
                "what it keeps caring about and what it refuses to do — are not "
                "built yet; this page is generated from a table that does not "
                "exist, and says so rather than appearing empty.*")
    out = ["# Commitments", "",
           "*What the being holds itself to, and beside each one what would "
           "show it had stopped. Nothing here was assigned to it; a commitment "
           "with no way to fail was refused at the door.*", ""]
    if not rows:
        out.append("*None yet. The being is asked once a night, and most "
                   "nights the answer is no.*")
    from newz.memory.provenance import what_shaped_commitment

    for r in rows:
        kind = _COMMITMENT_KIND.get(r["kind"], r["kind"])
        status = ("" if r["status"] == "standing"
                  else f" · `{_e(r['status'])}`")
        out.append(f"## {_e(r['statement'])}")
        out.append("")
        out.append(f"`{_e(kind)}`{status}")
        out.append("")
        out.append(f"*broken by: {_e(r['falsifier'])}*")
        # E4.3: what shaped it, and INV-033's flag. §8 asks that shaping
        # influences be traceable and open to challenge, and a commitment is
        # the one thing here the being authored about ITSELF — so a mix that
        # is all one source is an identity claim resting on one source, which
        # matters more than it does on an ordinary position.
        inf = what_shaped_commitment(conn, r["id"])
        if inf is not None:
            out.append("")
            if not inf.total:
                out.append("*shaped by: nothing traceable — this commitment "
                           "carries no resolvable evidence*")
            else:
                out.append(f"*shaped by {inf.total} episode(s) — the world "
                           f"{inf.share('world'):.0%} · people "
                           f"{inf.share('human'):.0%} · itself "
                           f"{inf.share('self'):.0%}*")
                top = inf.concentration
                if top and top[1] > 0.5:
                    out.append("")
                    out.append(f"*{top[1]:.0%} of this comes from one source: "
                               f"`{_e(top[0])}`*")
        for ch in changes.get(r["id"], []):
            carried = ("carried by a claim the world settled"
                       if ch["resolution_id"] else "no claim carried it")
            out.append("")
            out.append(f"***{_e(ch['kind'])}** {_day(ch['ts'])} — "
                       f"{_e(ch['reason'])} ({carried})*")
        out.append("")
    return "\n".join(out)


def _one_work(conn: sqlite3.Connection, row, m: Manifest) -> tuple[str, str]:
    """A piece at its own stable address (E3.4).

    Keyed by the row id, not by the signature or the title: a revised piece is
    the same piece and must keep its address, or every revision breaks whatever
    pointed at it. Stability is what makes an identifier worth citing, and it
    is a separate question from whether anyone may crawl it.
    """
    page = f"work/{row['id']}.md"
    m.record(page, "works", [row["id"]])
    keys = row.keys()
    sig = row["signature"] if "signature" in keys else None
    status = (row["status"] if "status" in keys else None) or "standing"
    meta = [_day(row["ts"])]
    if status == "retracted":
        meta.append("**retracted**")
    meta.append(f"on: {_e(row['subject_text'])}")
    body = [f"# {_e(row['title'])}", "",
            "*" + " · ".join(meta) + "*", "",
            _body(row["body"])]
    try:
        for rev in conn.execute(
                "SELECT * FROM work_revisions WHERE work_id=? ORDER BY ts",
                (row["id"],)):
            m.record(page, "work_revisions", [rev["id"]])
            body.append("")
            body.append(f"***{_e(rev['kind'])}** {_day(rev['ts'])} — "
                        f"{_e(rev['reason'])}*")
    except sqlite3.OperationalError:
        pass
    body.append("")
    body.append("*" + (
        f"signed {_e(sig[:16])}…" if sig
        else "unsigned — written before pieces were signed") + "*")
    return page, _page(row["title"], "\n".join(body), here="index")


def generate(conn: sqlite3.Connection, out_dir: Path, *, now: float) -> Manifest:
    """Write the whole surface. The directory is emptied of what this writes."""
    out_dir.mkdir(parents=True, exist_ok=True)
    m = Manifest(generated_at=now)

    pages = {
        "index.md": ("The work", _works(conn, m), "index"),
        "questions.md": ("Open questions", _questions(conn, m), "questions"),
        "errors.md": ("What it was wrong about", _errors(conn, m), "errors"),
        "commitments.md": ("Commitments", _commitments(conn, m), "commitments"),
        "read.md": ("The read", _read(conn, m), "read"),
    }
    for name, (title, body, here) in pages.items():
        (out_dir / name).write_text(_page(title, body, here=here), encoding="utf-8")

    # One stable address per piece, so a piece can be pointed at (E3.4).
    (out_dir / "work").mkdir(exist_ok=True)
    for row in conn.execute("SELECT * FROM works ORDER BY id"):
        name, page = _one_work(conn, row, m)
        (out_dir / name).write_text(page, encoding="utf-8")

    # No index, ever. A request rather than a permission — what actually keeps
    # the surface private is the bind address (newz/surface/serve.py).
    (out_dir / "robots.txt").write_text(
        "User-agent: *\nDisallow: /\n", encoding="utf-8")

    (out_dir / "manifest.json").write_text(
        json.dumps(m.as_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return m
