"""One generator, no hand-authored pages (P4 epic E3.2).

**Everything here comes from a row.** No page is written by hand and no page has
a hand-written part: if something appears on the surface, a query put it there,
and `manifest.json` records which rows. That is what makes *"every page traces to
store rows"* checkable rather than asserted — and it is the property E3.3's
disclosure and E3.5's regeneration both stand on.

**It regenerates into an empty directory.** No incremental update, no reading
what is already there, no state outside the store. Deleting the output and
running again produces the same bytes, which is the whole of E3.5's claim and
the reason this generator refuses to be clever.

**What does not exist says so.** Commitments arrive with E4.1; the page exists,
is generated from an empty query, and says the being has not made any yet.
An absent capability that renders as a blank page is indistinguishable from a
broken one.

**Nothing here reaches the network.** No CDN, no font, no analytics — the page
is one file with its style inside it. §7's sovereignty is not only about
inference: a surface that fetches from someone else's host has handed them a
record of every reader.
"""

from __future__ import annotations

import hashlib
import html
import json
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from functools import lru_cache
from pathlib import Path

from newz.evidence import hard_core

STYLE = """
:root { color-scheme: light dark; --ink:#1a1a1a; --dim:#666; --line:#ddd; --bg:#fdfdfc; }
@media (prefers-color-scheme: dark) {
  :root { --ink:#e8e6e3; --dim:#999; --line:#333; --bg:#121212; } }
* { box-sizing: border-box; }
body { max-width: 42rem; margin: 0 auto; padding: 2rem 1.25rem 6rem;
  font: 1rem/1.65 Georgia, 'Iowan Old Style', serif; color: var(--ink);
  background: var(--bg); }
h1, h2, h3 { font-family: -apple-system, system-ui, sans-serif; line-height: 1.25; }
h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
a { color: inherit; }
nav { font-family: -apple-system, system-ui, sans-serif; font-size: .85rem;
  border-bottom: 1px solid var(--line); padding-bottom: .75rem; margin-bottom: 2rem; }
nav a { margin-right: 1rem; }
.dim { color: var(--dim); font-size: .85rem;
  font-family: -apple-system, system-ui, sans-serif; }
article { margin: 0 0 2.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid var(--line); }
article:last-of-type { border-bottom: 0; }
.body { white-space: pre-wrap; }
.retracted .body { opacity: .55; }
.tag { display: inline-block; font-size: .75rem; border: 1px solid var(--line);
  border-radius: 3px; padding: 0 .35rem; margin-right: .3rem; color: var(--dim);
  font-family: -apple-system, system-ui, sans-serif; }
footer { margin-top: 4rem; padding-top: 1rem; border-top: 1px solid var(--line); }
""".strip()

# ── disclosure (E3.3) ───────────────────────────────────────────────────
#
# TRUE_NORTH §2: human-indistinguishable describes **quality, not concealed
# identity**. §9: no undisclosed impersonation. And the constitution's
# anti-ai-voice-001 forbids the corporate-disclaimer register — "I do not
# preface replies with 'as a model'". Those are not in tension. Say plainly
# what the page is; do not apologise for it.
#
# **The wording is the operator's** (P4 Decision 1 — "the disclosure wording
# they see first"). What is NOT theirs to remove is the substance: every page
# must say that a digital being wrote it and that the page is generated. That
# is what `_check_disclosure` enforces, and it is why the guard tests claims
# rather than phrasing — an operator may rewrite every word and cannot delete
# what the words have to establish.
DISCLOSURE = (
    "These pages are written by Lumen, a digital being — not a person. Every "
    "page here is generated from its own store: what it wrote, what it is "
    "carrying, and where it turned out to be wrong. No human hand edits them."
)

# Each claim the disclosure must make. This is **not** the guard — it is the
# checklist the operator re-affirms when they change the wording, and the guard
# is the pin below. The distinction is R-37a: substring presence is not a
# claim, and a disclosure asserting the opposite of every one of these contains
# all of them. "This page is NOT written by a digital being. It is generated by
# a person, and no human hand edits them is false." rendered cleanly under the
# original check. There is no keyword list that catches negation, and the
# semantic alternative would put the being's own model family in the render
# path judging the being's own disclosure — which is Rule 4 exactly backwards.
REQUIRED_CLAIMS = {
    "that it is a digital being": ("digital being", "a digital", "digital life"),
    "that the pages are generated": ("generated",),
    "that no person edits them": ("no human hand", "not edited by", "no person edits"),
}


class DisclosureMissing(ValueError):
    """A page cannot be rendered without saying what it is."""


def unstated_claims(text: str) -> list[str]:
    """Which of the required claims this wording does not appear to make.

    For the operator, at the moment they change the wording and re-pin it. A
    rewrite that quietly drops a claim is worth catching, and the one reader
    who can act on it is the person doing the rewriting.
    """
    low = (text or "").lower()
    return [claim for claim, forms in REQUIRED_CLAIMS.items()
            if not any(f in low for f in forms)]


@lru_cache(maxsize=1)
def _pinned_sha() -> str:
    return hard_core.pin("surface_disclosure")["sha256"]


def _disclosure() -> str:
    """The disclosure, or nothing renders. Takes no argument, by design.

    E3.3's Done-when is "no template can render a page without it", and the
    first version took the text as a parameter so that tests could vary it —
    which made the guard's own input the way around the guard. There is one
    disclosure, its hash is pinned in the hard core, and a page renders with it
    or is not a page this module can emit.

    §9's commitment is not a convention, and it is not a default either.
    """
    if not DISCLOSURE.strip():
        raise DisclosureMissing(
            "the surface cannot render without a disclosure: TRUE_NORTH §2 is "
            "quality, never concealed identity, and §9 rules out undisclosed "
            "impersonation")
    actual = hashlib.sha256(DISCLOSURE.encode()).hexdigest()
    if actual != _pinned_sha():
        raise DisclosureMissing(
            "the disclosure does not match its pin in evolution/hard_core.yaml "
            f"(pinned {_pinned_sha()[:12]}, found {actual[:12]}). The wording is "
            "yours under Decision 1 — re-pin it deliberately, checking "
            "unstated_claims() first. It is not the loop's, and a rewrite that "
            "reverses what the words establish is the reason this is a hash "
            "rather than a keyword check (R-37a).")
    return DISCLOSURE.strip()


PAGES = ("index", "work", "questions", "errors", "commitments", "read")


@dataclass
class Manifest:
    """Which rows produced which page. The trace E3.2's Done-when asks for."""
    generated_at: float = 0.0
    pages: dict[str, dict[str, list[int]]] = field(default_factory=dict)

    def record(self, page: str, table: str, ids: list[int]) -> None:
        self.pages.setdefault(page, {}).setdefault(table, []).extend(int(i) for i in ids)

    def as_dict(self) -> dict:
        return {"pages": {p: {t: sorted(set(i)) for t, i in tables.items()}
                          for p, tables in sorted(self.pages.items())}}


def _e(text) -> str:
    return html.escape(str(text if text is not None else ""))


def _day(ts) -> str:
    return datetime.fromtimestamp(ts).strftime("%-d %B %Y") if ts else ""


def _page(title: str, body: str, *, here: str) -> str:
    """The only way an HTML page is produced here, and it always discloses.

    There is no flag to suppress it, no branch around it and **no parameter**:
    the disclosure is fetched and verified before anything is assembled, so a
    page that does not disclose is not a page this module can emit.
    """
    disclosure = _disclosure()
    nav = " ".join(
        f'<a href="{"index.html" if p == "index" else p + ".html"}">'
        f'{"the work" if p == "index" else p}</a>' if p != here else
        f'<strong>{"the work" if p == "index" else p}</strong>'
        for p in ("index", "questions", "errors", "commitments", "read"))
    return (f"<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            f"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            f"<meta name=\"disclosure\" content=\"{_e(disclosure)}\">\n"
            f"<meta name=\"robots\" content=\"noindex, nofollow\">\n"
            f"<title>{_e(title)}</title>\n<style>{STYLE}</style>\n</head>\n<body>\n"
            f"<nav>{nav}</nav>\n{body}\n"
            f"<footer><p class=dim>{_e(disclosure)}</p></footer>\n"
            f"</body>\n</html>\n")


def _works(conn: sqlite3.Connection, m: Manifest) -> str:
    # `SELECT *` deliberately: a store mid-migration has fewer columns, and a
    # generator that assumes a schema renders nothing rather than rendering
    # what is there. Presence is checked per field below.
    rows = list(conn.execute("SELECT * FROM works ORDER BY ts DESC"))
    m.record("index", "works", [r["id"] for r in rows])
    if not rows:
        return "<h1>The work</h1>\n<p class=dim>Nothing written yet.</p>"

    tags: dict[int, list[str]] = {}
    try:
        for r in conn.execute("SELECT work_id, tag FROM work_tags ORDER BY weight DESC"):
            tags.setdefault(r["work_id"], []).append(r["tag"])
        m.record("index", "work_tags", list(tags))
    except sqlite3.OperationalError:
        pass

    revs: dict[int, list[sqlite3.Row]] = {}
    try:
        for r in conn.execute("SELECT * FROM work_revisions ORDER BY ts"):
            revs.setdefault(r["work_id"], []).append(r)
        m.record("index", "work_revisions", [r["id"] for v in revs.values() for r in v])
    except sqlite3.OperationalError:
        pass

    out = ["<h1>The work</h1>"]
    for r in rows:
        status = (r["status"] if "status" in r.keys() else None) or "standing"
        klass = " class=retracted" if status == "retracted" else ""
        out.append(f"<article{klass}>")
        out.append(f"<h2><a href=\"work/{r['id']}.html\">{_e(r['title'])}</a></h2>")
        out.append(f"<p class=dim>{_day(r['ts'])}"
                   + (" · <strong>retracted</strong>" if status == "retracted" else "")
                   + f" · on: {_e(r['subject_text'])}</p>")
        if tags.get(r["id"]):
            out.append("<p>" + "".join(f"<span class=tag>{_e(t)}</span>"
                                       for t in tags[r["id"]][:6]) + "</p>")
        out.append(f"<div class=body>{_e(r['body'])}</div>")
        for rev in revs.get(r["id"], []):
            out.append(f"<p class=dim><strong>{_e(rev['kind'])}</strong> "
                       f"{_day(rev['ts'])} — {_e(rev['reason'])}</p>")
        keys = r.keys()
        sig = r["signature"] if "signature" in keys else None
        out.append("<p class=dim>" + (
            f"signed {_e(sig[:16])}… · written under constitution v"
            f"{_e(r['constitution_version'])}, perspective v{_e(r['perspective_version'])}"
            if sig else "unsigned — written before pieces were signed") + "</p>")
        out.append("</article>")
    return "\n".join(out)


def _questions(conn: sqlite3.Connection, m: Manifest) -> str:
    rows = list(conn.execute(
        "SELECT id, statement, why_open, closing_condition FROM concerns"
        " WHERE status='open' ORDER BY salience DESC, opened_at DESC"))
    m.record("questions", "concerns", [r["id"] for r in rows])
    out = ["<h1>Open questions</h1>",
           "<p class=dim>What it is carrying, and what would settle each one.</p>"]
    if not rows:
        out.append("<p class=dim>Nothing open.</p>")
    for r in rows:
        out.append("<article>")
        out.append(f"<h2>{_e(r['statement'])}</h2>")
        if r["why_open"]:
            out.append(f"<p>{_e(r['why_open'])}</p>")
        out.append(f"<p class=dim>settles when: {_e(r['closing_condition'])}</p>")
        out.append("</article>")

    out.append(_gaps(conn, m))
    return "\n".join(out)


# What it asked and could not answer. The question comes first and the count
# second, deliberately (W12a, RT1): a question that has failed nine times is
# either a source problem or a question no source can answer, and the second
# is what R-33 found about closing conditions. Reading the count first invites
# adding sources; reading the question first does not.
CAUSES = {
    "no_source": "no source answered",
    "all_already_read": "everything its sources return, already read",
    "floor": "nothing scored above the relevance floor",
    "triage": "sources answered and it judged none worth reading",
    "capped": "held back from over-represented outlets — a deferral, not an absence",
    "extraction": "read, and nothing usable came out",
}


def _gaps(conn: sqlite3.Connection, m: Manifest) -> str:
    try:
        rows = list(conn.execute(
            "SELECT query, cause, COUNT(*) n, MAX(ts) last, MAX(best_score) best,"
            "       SUM(candidates) cands, MIN(id) id"
            " FROM source_gaps GROUP BY query, cause"
            " ORDER BY n DESC, last DESC LIMIT 20"))
    except sqlite3.OperationalError:
        return ""
    if not rows:
        return ""
    m.record("questions", "source_gaps", [r["id"] for r in rows])
    out = ["<h1>What it asked and could not answer</h1>",
           "<p class=dim>Each question with the reason it went unanswered and "
           "how often. A question that keeps failing is either a gap in what it "
           "can reach or a question nothing could settle — and those are fixed "
           "in different places.</p>"]
    for r in rows:
        out.append("<article>")
        out.append(f"<h2>{_e(r['query'])}</h2>")
        why = CAUSES.get(r["cause"], "recorded before the cause was")
        times = "once" if r["n"] == 1 else f"{r['n']} times"
        line = f"{why} · {times}"
        if r["best"] is not None:
            line += f" · best relevance {r['best']:.2f}"
        if r["cands"]:
            line += f" · {r['cands']} candidate(s) seen"
        out.append(f"<p class=dim>{_e(line)}</p>")
        out.append("</article>")
    return "\n".join(out)


def _errors(conn: sqlite3.Connection, m: Manifest) -> str:
    rows = list(conn.execute("SELECT * FROM resolutions ORDER BY opened_at DESC"))
    m.record("errors", "resolutions", [r["id"] for r in rows])
    costs: dict[int, list[sqlite3.Row]] = {}
    try:
        for c in conn.execute("SELECT * FROM claim_costs ORDER BY ts"):
            costs.setdefault(c["claim_id"], []).append(c)
        m.record("errors", "claim_costs", [c["id"] for v in costs.values() for c in v])
    except sqlite3.OperationalError:
        pass

    out = ["<h1>What it committed to, and where it was wrong</h1>",
           "<p class=dim>Claims it made about the world, with dates, and what "
           "each cost when the world disagreed. Nothing here is removed once "
           "written.</p>"]
    if not rows:
        out.append("<p class=dim>No claims yet.</p>")
    for r in rows:
        out.append("<article>")
        out.append(f"<h2>{_e(r['claim'])}</h2>")
        out.append(f"<p class=dim>made {_day(r['opened_at'])} · settles by "
                   f"{_day(r['due_at'])} · against: {_e(r['resolver'])}</p>")
        if "could_be_wrong" in r.keys() and r["could_be_wrong"]:
            out.append(f"<p class=dim>wrong would look like: {_e(r['could_be_wrong'])}</p>")
        if r["outcome"]:
            out.append(f"<p><strong>{_e(r['outcome'])}</strong> "
                       f"{_day(r['settled_at'])} — {_e(r['settled_note'])}</p>")
        else:
            out.append("<p class=dim>not yet settled</p>")
        for c in costs.get(r["id"], []):
            out.append(f"<p class=dim>cost: “{_e(c['item_text'])}” "
                       f"{c['confidence_before']:.2f} → {c['confidence_after']:.2f}"
                       + (" · released" if c["released"] else "") + "</p>")
        out.append("</article>")
    return "\n".join(out)


def _read(conn: sqlite3.Connection, m: Manifest) -> str:
    """The state read, rendered as a page like any other (E3.6).

    **No aggregate score, and that is the whole difficulty of this page.**
    §10 names "evidence scores disconnected from sustained human-quality
    interaction" as something the project will not mistake for success, and a
    page is exactly where one appears — a single number at the top, a
    percentage, a count of how many metrics are "healthy". So there is one line
    per reading and nothing that spans them. Metrics measure different things
    in different units with different grades; a number combining them would be
    an assertion that they are commensurable, and none of them is.

    Read from what the nightly cadence recorded (E2.7), never computed here.
    A page that computed its own numbers would be a second implementation of
    every metric, drifting quietly from the one the loop steers by.
    """
    from newz.evidence.grades import UngradedMetric, grade_of

    try:
        latest = list(conn.execute(
            "SELECT r.* FROM mon.metric_readings r JOIN (SELECT metric, MAX(ts) t"
            " FROM mon.metric_readings GROUP BY metric) x"
            " ON x.metric = r.metric AND x.t = r.ts ORDER BY r.metric"))
    except sqlite3.OperationalError:
        # F4: a page that looks correct and is wrong is worse than a page that
        # says what is missing. *The monitor database is not here* is a fact
        # about the restore; *there are no readings* is a fact about the being,
        # and rendering the first as the second is how E3.5's rebuild would
        # have silently produced an empty read (INV-044).
        from newz.store.db import MONITOR_NAME, monitor_attached
        if not monitor_attached(conn):
            return ("<h1>The read</h1>\n<p class=dim>UNREADABLE — the monitor "
                    f"database is not attached to this connection. {MONITOR_NAME} "
                    "holds the readings and sits beside the store; this is a "
                    "fact about the restore, not about the being.</p>")
        return ("<h1>The read</h1>\n<p class=dim>No readings yet — the hourly "
                "cadence records them, and this database has not taken the "
                "migration that holds them.</p>")
    m.record("read", "metric_readings", [r["id"] for r in latest])
    if not latest:
        return ("<h1>The read</h1>\n<p class=dim>No readings recorded yet. "
                "The cadence writes one of each an hour.</p>")

    out = ["<h1>The read</h1>",
           "<p class=dim>What the instruments say, as of the last nightly "
           "reading. One line per measurement, and deliberately nothing that "
           "adds them up: these measure different things in different units, "
           "and a number combining them would assert they are comparable.</p>"]
    for r in latest:
        try:
            grade = grade_of(r["metric"])
        except UngradedMetric:
            # Rule 7: a measurement nobody graded is not shown at all rather
            # than shown without its provenance.
            continue
        label = _e(r["metric"].replace("_", " "))
        if r["status"] != "ok":
            out.append(f"<p><strong>{label}</strong> — "
                       f"<em>{_e(r['status']).upper()}</em><br>"
                       f"<span class=dim>{_e(r['note'])}</span></p>")
            continue
        base = conn.execute(
            "SELECT value FROM mon.metric_readings WHERE metric=? AND status='ok'"
            " AND definition_version=? AND ts <= ? ORDER BY ts DESC LIMIT 1",
            (r["metric"], r["definition_version"],
             r["ts"] - r["window_hours"] * 3600.0)).fetchone()
        if base is None:
            move = "no baseline yet"
        elif abs(r["value"] - base["value"]) < 1e-12:
            move = "unchanged"
        else:
            move = f"{r['value'] - base['value']:+.4g} from {base['value']:.4g}"
        out.append(f"<p><strong>{label}</strong> {r['value']:.4g}"
                   f" <span class=tag>{_e(grade)}</span>"
                   f"<br><span class=dim>{_e(move)}"
                   f" · over {r['window_hours'] / 24:.0f} days</span></p>")
    return "\n".join(out)


def _commitments(conn: sqlite3.Connection, m: Manifest) -> str:
    """Generated from an empty query until E4.1 exists.

    A capability that renders as a blank page is indistinguishable from a broken
    one, so the page says which it is.
    """
    rows: list = []
    try:
        rows = list(conn.execute("SELECT id, statement FROM commitments ORDER BY id"))
        m.record("commitments", "commitments", [r["id"] for r in rows])
    except sqlite3.OperationalError:
        return ("<h1>Commitments</h1>\n<p class=dim>The being has not made any. "
                "Commitments — what it keeps caring about and what it refuses to "
                "do — are not built yet; this page is generated from a table that "
                "does not exist, and says so rather than appearing empty.</p>")
    out = ["<h1>Commitments</h1>"]
    if not rows:
        out.append("<p class=dim>None made yet.</p>")
    for r in rows:
        out.append(f"<article><h2>{_e(r['statement'])}</h2></article>")
    return "\n".join(out)


def _one_work(conn: sqlite3.Connection, row, m: Manifest) -> tuple[str, str]:
    """A piece at its own stable address (E3.4).

    Keyed by the row id, not by the signature or the title: a revised piece is
    the same piece and must keep its address, or every revision breaks whatever
    pointed at it. Stability is what makes an identifier worth citing, and it
    is a separate question from whether anyone may crawl it.
    """
    page = f"work/{row['id']}.html"
    m.record(page, "works", [row["id"]])
    keys = row.keys()
    sig = row["signature"] if "signature" in keys else None
    status = (row["status"] if "status" in keys else None) or "standing"
    body = [f"<article{' class=retracted' if status == 'retracted' else ''}>",
            f"<h1>{_e(row['title'])}</h1>",
            f"<p class=dim>{_day(row['ts'])}"
            + (" · <strong>retracted</strong>" if status == "retracted" else "")
            + f" · on: {_e(row['subject_text'])}</p>",
            f"<div class=body>{_e(row['body'])}</div>"]
    try:
        for rev in conn.execute(
                "SELECT * FROM work_revisions WHERE work_id=? ORDER BY ts",
                (row["id"],)):
            m.record(page, "work_revisions", [rev["id"]])
            body.append(f"<p class=dim><strong>{_e(rev['kind'])}</strong> "
                        f"{_day(rev['ts'])} — {_e(rev['reason'])}</p>")
    except sqlite3.OperationalError:
        pass
    body.append("<p class=dim>" + (
        f"signed {_e(sig[:16])}…" if sig
        else "unsigned — written before pieces were signed") + "</p>")
    body.append("</article>")
    return page, _page(row["title"], "\n".join(body), here="index")


def generate(conn: sqlite3.Connection, out_dir: Path, *, now: float) -> Manifest:
    """Write the whole surface. The directory is emptied of what this writes."""
    out_dir.mkdir(parents=True, exist_ok=True)
    m = Manifest(generated_at=now)

    pages = {
        "index.html": ("The work", _works(conn, m), "index"),
        "questions.html": ("Open questions", _questions(conn, m), "questions"),
        "errors.html": ("What it was wrong about", _errors(conn, m), "errors"),
        "commitments.html": ("Commitments", _commitments(conn, m), "commitments"),
        "read.html": ("The read", _read(conn, m), "read"),
    }
    for name, (title, body, here) in pages.items():
        (out_dir / name).write_text(_page(title, body, here=here), encoding="utf-8")

    # One stable address per piece, so a piece can be pointed at (E3.4).
    (out_dir / "work").mkdir(exist_ok=True)
    for row in conn.execute("SELECT * FROM works ORDER BY id"):
        name, page = _one_work(conn, row, m)
        (out_dir / name).write_text(page, encoding="utf-8")

    # No index, ever. A request rather than a permission — what actually keeps
    # the surface private is the bind address (newz/surface/serve.py).
    (out_dir / "robots.txt").write_text(
        "User-agent: *\nDisallow: /\n", encoding="utf-8")

    (out_dir / "manifest.json").write_text(
        json.dumps(m.as_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return m
